### ISSUE TITLE
selenium-python-helium integration

### ISSUE THREAD

**Issue by petrisorureche** [fungaegis/pytest-failed-screenshot#1]
**selenium-python-helium**

It will be great if we can integrate _selenium-python-helium_ https://github.com/mherrmann/selenium-python-helium in this project.

https://selenium-python-helium.readthedocs.io/en/latest/api.html

I try with selenium https://pypi.org/project/selenium/ library and works fine, all screenshots are saved in screenshot directory.

With Helium screenshots are not saved.

**Comment by fungaegis** [comment]
I've added support for helium, but I didn't know about helium before, and I didn't use helium project. I've tested it with a simple example. I hope you can use it to see if it works normally.
Update to the latest version, looking forward to your feedback

**Comment by petrisorureche** [comment]
Hi @fungaegis , you already made the changes? I'm asking because last commit is 2 months old.

**Comment by fungaegis** [comment]
I just forgot to push to GitHub. Now I've pushed. Pypi has already been updated（ https://pypi.org/project/pytest-failed-screenshot/ ）You can update to the latest through pip

**Comment by petrisorureche** [comment]
Hi @fungaegis just tested, everything works as expected. I would like to contribute to this project, if you agree with that.

**Comment by fungaegis** [comment]
Project is Tim license, welcome your contribution.Looking forward to your pr.

**Comment by petrisorureche** [comment]
it is my first PR on github so I receive this error, any idea?

`git push origin HEAD
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcmcore-tlsverify for more information.
info: please complete authentication in your browser...
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcmcore-tlsverify for more information.
remote: Permission to fungaegis/pytest-failed-screenshot.git denied to petrisorionel.
fatal: unable to access 'https://github.com/fungaegis/pytest-failed-screenshot.git/': The requested URL returned error: 403
`
