### ISSUE TITLE
don't install allure-pytest if there is allure-pytest-bdd

### ISSUE THREAD

**Issue by sqandrew** [fungaegis/pytest-failed-screenshot#3]
Hi there!
my framework is pytest-bdd based and uses **allure-pytest-bdd** instead of **allure-pytest**. Installing pytest-failed-screenshot with allure-pytest leads to their conflict
`ValueError: option names {'--alluredir'} already added
`

Thanks

**Comment by fungaegis** [comment]
hi @sqandrew  `pytest-failed-screenshot` only uses the `allure.attach()` function of `allure`. It should be that `allure-pytest` is installed when the `pytest-failed-screenshot` is installed, resulting in a conflict with `allure-pytest-bdd`. Try to uninstall `allure-pytest` and then reinstall `allure-pytest-bdd`

**Comment by sqandrew** [comment]
thanks for the answer, it helped to deal with 
`ValueError: option names {'--alluredir'} already added`

however, it looks like pytest-bdd doesn't work with pytest-failed-screenshot.
